[platformio]
default_envs = esp32dev
src_dir = firmware/jemuran_otomatis/src

[env:esp32dev]
platform = espressif32 @ 7.1.3
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    blynkkk/Blynk @ 1.3.2
    waspinator/AccelStepper @ 1.64.0
build_flags = -Wall -Wextra
